# Generated by Django 4.1.3 on 2023-05-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0002_banner_customwebpage_webpagebannerm2m_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="name",
            field=models.CharField(blank=True, max_length=500, verbose_name="Nombre"),
        ),
    ]
