version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    command: /bin/sh -c "entrypoint.sh"
    volumes:
      - .:/www
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: "postgres:13-alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ghm_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
