FROM python:3.8-alpine

ENV PYTHONUNBUFFERED 1

RUN apk --update add \
    build-base \
    postgresql \
    postgresql-dev \
    gcc \
    python3-dev \
    musl-dev \
    libpq \
    # pillow dependencies
    jpeg-dev \
    zlib-dev \
    # pycurl dependencies
    curl-dev

RUN mkdir /www
WORKDIR /www
RUN mkdir /requirements
COPY ./requirements/ ./requirements
RUN pip3 install -r ./requirements/prod.txt

COPY . /www/
